:concurrency: 10

staging:
  :pidfile: /var/www/wattle/shared/tmp/pids/sidekiq.pid

production:
  :pidfile: /var/www/wattle/shared/tmp/pids/sidekiq.pid

:queues:
  - [prod_wat_creation, 50]
  - [high, 5]
  - default
  - mailers
  - searchkick
