development:
  host: "http://localhost:3000"
  disabled: false

test:
  disabled: true

staging:
  host: <%= WatConfig.secret_value 'WATTLE_HOST' %>
  disabled: false

production:
  host: <%= WatConfig.secret_value 'WATTLE_HOST' %>
  disabled: false
